### ISSUE TITLE
ImportError: No module named graph_editor

### ISSUE THREAD

**Issue by mbeach42** [bstriner/keras-adversarial#17]
Hi, 

I just installed keras-adversarial, and tried to run the MNIST example. I got this error:

```
Using TensorFlow backend.
/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: Deprecation Warning: This module was deprecated in version 0.18 in favor of the model_sele                 ction module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this                  module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/keras_adversarial/__init__.py", line 1, in                  <module>
  File "build/bdist.linux-x86_64/egg/keras_adversarial/adversarial_model.py", li                 ne 8, in <module>
  File "build/bdist.linux-x86_64/egg/keras_adversarial/adversarial_utils.py", li                 ne 7, in <module>
  File "build/bdist.linux-x86_64/egg/keras_adversarial/backend/__init__.py", lin                 e 4, in <module>
  File "build/bdist.linux-x86_64/egg/keras_adversarial/backend/tensorflow_backen                 d.py", line 3, in <module>
ImportError: No module named graph_editor
```
Do you know what this graph_editor module is?

Running on Bash on Windows 10.

**Comment by bstriner** [comment]
What TF version are you on? Should be able to just `print tensorflow.__version__`. That module is in the right place in current 1.1 but I don't know if it has moved around.

It is in the contrib module, so maybe that wasn't included in whatever version you are running.

https://www.tensorflow.org/api_guides/python/contrib.graph_editor

Graph editing is required for lots of advanced optimization. It is built-in to Theano. It was added to TF to try to compete with Theano but that might only have happened recently.

BTW, how is TF on bash on Windows working for you? I've been stuck using only Theano on Windows. Performance and CUDA all works out OK?

Cheers
