### ISSUE TITLE
'AdversarialModel' object has no attribute '_feed_output_shapes'

### ISSUE THREAD

**Issue by atulapra** [bstriner/keras-adversarial#49]
I tried creating an adversarial network, when I got the following error. (I'm using python 3.5.3)

Traceback (most recent call last):
  File "gan.py", line 69, in <module>
    history = model.fit(x=train_x, y=gan_targets(train_x.shape[0]), epochs=10, batch_size=batch_size)
  File "/home/atul/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1581, in fit
    batch_size=batch_size)
  File "/home/atul/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1399, in _standardize_user_data
    for output_shape, loss_fn in zip(self._feed_output_shapes, self._feed_loss_fns):
AttributeError: 'AdversarialModel' object has no attribute '_feed_output_shapes'

**Comment by singularitiai** [comment]
Happened with me when I installed it using pip. Install it by cloing the repo, and it'll work. The file adversarial_model.py is different in the pip version and doesn't have _feed_output_shapes

**Comment by itachi0071998** [comment]
I did that but I am still getting the same error

**Comment by sinjorjob** [comment]
I am getting the same error.
the environment is below.
Keras                2.1.2
keras-adversarial    0.0.3
Keras-Applications   1.0.4
Keras-Preprocessing  1.0.2
tensorflow           1.8.0

OS: windows10

it there any  solution?
