### ISSUE TITLE
Error: _gru_ops.dll not found // tensorflow 1.6.0, python 3.6.1

### ISSUE THREAD

**Issue by parasange** [bstriner/keras-adversarial#54]
Get the following error, when running example_gan.py with tensorflow 1.6.0 under Python 3.6.1.
Had no problem with tensorflow 0.12.1, Python 3.5

Traceback (most recent call last):
  File ".\example_gan.py", line 13, in <module>
    from keras_adversarial.image_grid_callback import ImageGridCallback
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Python_3_6\lib\site-packages\keras_adversarial-0.0.3-py3.6.egg\keras_adversarial\__init__.py", line 1, in <module>
    from .adversarial_model import AdversarialModel
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Python_3_6\lib\site-packages\keras_adversarial-0.0.3-py3.6.egg\keras_adversarial\adversarial_model.py", line 8, in <module>
    from .adversarial_utils import fix_names, merge_updates
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Python_3_6\lib\site-packages\keras_adversarial-0.0.3-py3.6.egg\keras_adversarial\adversarial_utils.py", line 7, in <module>
    from .backend import unpack_assignment, variable_key
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Python_3_6\lib\site-packages\keras_adversarial-0.0.3-py3.6.egg\keras_adversarial\backend\__init__.py", line 4, in <module>
    from .adversarial_optimizers import AdversarialOptimizerScheduled
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Python_3_6\lib\site-packages\keras_adversarial-0.0.3-py3.6.egg\keras_adversarial\backend\tensorflow_backend.py", line 3, in <module>
  File "C:\Python_3_6\lib\site-packages\tensorflow\contrib\__init__.py", line 23, in <module>
    from tensorflow.contrib import bayesflow
  File "C:\Python_3_6\lib\site-packages\tensorflow\contrib\bayesflow\__init__.py", line 28, in <module>
    from tensorflow.contrib.bayesflow.python.ops import layers
  File "C:\Python_3_6\lib\site-packages\tensorflow\contrib\bayesflow\python\ops\layers.py", line 26, in <module>
    from tensorflow.contrib.bayesflow.python.ops.layers_conv_variational import *
  File "C:\Python_3_6\lib\site-packages\tensorflow\contrib\bayesflow\python\ops\layers_conv_variational.py", line 22, in <module>
    from tensorflow.contrib.bayesflow.python.ops import layers_util
  File "C:\Python_3_6\lib\site-packages\tensorflow\contrib\bayesflow\python\ops\layers_util.py", line 24, in <module>
    from tensorflow.contrib.distributions.python.ops import deterministic as deterministic_lib
  File "C:\Python_3_6\lib\site-packages\tensorflow\contrib\distributions\__init__.py", line 38, in <module>
    from tensorflow.contrib.distributions.python.ops.estimator import *
  File "C:\Python_3_6\lib\site-packages\tensorflow\contrib\distributions\python\ops\estimator.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
  File "C:\Python_3_6\lib\site-packages\tensorflow\contrib\learn\__init__.py", line 92, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "C:\Python_3_6\lib\site-packages\tensorflow\contrib\learn\python\__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "C:\Python_3_6\lib\site-packages\tensorflow\contrib\learn\python\learn\__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "C:\Python_3_6\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\__init__.py", line 303, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dynamic_rnn_estimator import DynamicRnnEstimator
  File "C:\Python_3_6\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\dynamic_rnn_estimator.py", line 27, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import rnn_common
  File "C:\Python_3_6\lib\site-packages\tensorflow\contrib\learn\python\learn\estimators\rnn_common.py", line 22, in <module>
    from tensorflow.contrib import rnn as contrib_rnn
  File "C:\Python_3_6\lib\site-packages\tensorflow\contrib\rnn\__init__.py", line 83, in <module>
    from tensorflow.contrib.rnn.python.ops.gru_ops import *
  File "C:\Python_3_6\lib\site-packages\tensorflow\contrib\rnn\python\ops\gru_ops.py", line 33, in <module>
    resource_loader.get_path_to_datafile("_gru_ops.so"))
  File "C:\Python_3_6\lib\site-packages\tensorflow\contrib\util\loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "C:\Python_3_6\lib\site-packages\tensorflow\python\framework\load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "C:\Python_3_6\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: C:\Python_3_6\lib\site-packages\tensorflow\contrib\rnn\python\ops\_gru_ops.dll not found

**Comment by Mystar-x** [comment]
How to solve this problem ?

**Comment by MrGo2008** [comment]
I met the same issue,
Here is my solution.
1,pip uninstall tensorflow
2,conda install tensorflow
Reason:
tensorflow-gpu and tensorflow version mismatch.
