### ISSUE TITLE
Issues with Keras 2.2.0

### ISSUE THREAD

**Issue by SnowMasaya** [bstriner/keras-adversarial#60]
It seems that there are some issues with the latest version of Keras 2.2.0

I try to use keras-adversarial with kears 2.2.0 but it doesen't work.

```
Traceback (most recent call last):
File "example_gan_convolutional.py", line 109, in <module>
player_names=["generator", "discriminator"])
File "C:\Users\MasayaOgushi\Anaconda3\envs\deep-learning-keras\lib\site-packages\keras_adversarial\adversarial_model.py", line 47, in init
self.layers = []
File "C:\Users\MasayaOgushi\Anaconda3\envs\deep-learning-keras\lib\site-packages\keras\engine\network.py", line 323, in setattr
super(Network, self).setattr(name, value)
AttributeError: can't set attribute
```

Any help? is this going to be fixed? Thanks

**Comment by sukhadj** [comment]
I am getting the same issue.

**Comment by mValentino91** [comment]
I got the same problem using Keras 2.2.0. It seems to be an error caused by some incompatibilities. I tried out keras-adversarial with Keras 2.1.2 and it works.

**Comment by sukhadj** [comment]
It worked for me when I install it by cloning the repository. The pip version has different adversarial_model.py than repo.

**Comment by ussaema** [comment]
@sukhadj so it worked with keras 2.2.0 for you ?

**Comment by sukhadj** [comment]
@ussaema No it isn't working with keras 2.2.0. I was getting the same issues with keras 2.1.2 also.Hence I tried installing it through repo. But its not working with 2.2.0 whatsoever.

**Comment by yxhhh** [comment]
I have the same problem. Have you solved it?

**Comment by ussaema** [comment]
I am not using this module anymore. I created my own module for GANs for Kreas 2.2.x. check https://github.com/ussaema/Vector_Matrix_CapsuleGAN

**Comment by bonorico** [comment]
Hi, same issue here running 'example_gan.py' with python2.7 and 
Keras                         2.2.4      
keras-adversarial             0.0.3      
Keras-Applications            1.0.7      
Keras-Preprocessing           1.0.9      

in virtualenv. OS: Ubuntu 18.4. I typically get the error by attempting to set up AdversarialModel().

**Comment by 945226956** [comment]
really hop to fix it :）
