### ISSUE TITLE
Error while running examples/example_gan_convolutional.py

### ISSUE THREAD

**Issue by anujanegi** [bstriner/keras-adversarial#66]
Error:

Traceback (most recent call last):
  File "examples/example_gan_convolutional.py", line 102, in <module>
    player_names=["generator", "discriminator"])
  File "/usr/local/lib/python3.6/dist-packages/keras_adversarial-0.0.3-py3.6.egg/keras_adversarial/adversarial_model.py", line 47, in __init__
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 323, in __setattr__
    super(Network, self).__setattr__(name, value)
AttributeError: can't set attribute

**Comment by BettyWhcy** [comment]
I have the same problem. Do you solve it now?
