### ISSUE TITLE
example_gan.py cannot set attribute error

### ISSUE THREAD

**Issue by yuvaramsingh94** [bstriner/keras-adversarial#67]
hi . I am trying to run the example_gan.py code but I am facing issue with initializing the model . keras keeps throwing cannot set attributes error .

My env :
python 3.7
tensorflow 1.13.1
keras 2.2.4
keras-adversarial 0.0.3

`==================================================================================================
Total params: 2,946,577
Trainable params: 2,946,577
Non-trainable params: 0
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "example_gan.py", line 118, in <module>
    main()
  File "example_gan.py", line 114, in main
    latent_dim=latent_dim)
  File "example_gan.py", line 68, in example_gan
    player_names=["generator", "discriminator"])
  File "C:\Users\vmvijayayuvaram.s\AppData\Local\Continuum\anaconda3\envs\tf_gpu_1\lib\site-packages\keras_adversarial-0.0.3-py3.7.egg\keras_adversarial\adversarial_model.py", line 47, in __init__
  File "C:\Users\vmvijayayuvaram.s\AppData\Local\Continuum\anaconda3\envs\tf_gpu_1\lib\site-packages\keras\engine\network.py", line 316, in __setattr__
    super(Network, self).__setattr__(name, value)
AttributeError: can't set attribute
`

**Comment by BettyWhcy** [comment]
I have the same problem. Do you solve it now?

**Comment by yuvaramsingh94** [comment]
no . i haven't found any solution
